import Head from 'next/head'
import Title from '../components/Title'
import Count from '../components/Count'
import Button from '../components/Button'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title text="title" />
        <Count />
        <Button />
      </main>
    </div>
  )
}

export default Home
