import Head from 'next/head'
import { useState, useCallback, useMemo, useRef, forwardRef, useImperativeHandle } from 'react'
import Title from '../components/Title'
import Count from '../components/Count'
import Button from '../components/Button'

const FuncyInput = forwardRef((props, ref) => {
  const inputRef = useRef({})

  useImperativeHandle(ref, () => {
    return {
      setFocus() {
        console.log('setFocus')
        inputRef.current.focus()
        inputRef.current.value = 1
      },
    }
  })

  return <input ref={inputRef} />
})

const Home = () => {
  const ref = useRef({})
  const [height, setHeight] = useState(160)
  const [weight, setWeight] = useState(50)

  const incrementHeight = useCallback(() => setHeight(height + 1))
  const incrementWeight = useCallback(() => setWeight(weight + 1))

  const isEven = useMemo(() => {
    console.log('身長')
    return height % 2 === 0
  }, [height])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title text="title" />
        <p>
          身長 {height} は {isEven ? '偶数' : '奇数'}
        </p>
        <Count text="身長" count={height} />
        <Count text="体重" count={weight} />
        <Button handleClick={incrementHeight}>身長+1</Button>
        <Button handleClick={incrementWeight}>体重+1</Button>
      </main>

      <div>
        <h2>useImperativeHandle</h2>
        <FuncyInput ref={ref} />
        <button
          onClick={() => {
            console.log('ref', ref)
            ref.current.setFocus()
          }}
        >
          click
        </button>
      </div>
    </div>
  )
}

export default Home
